import mongoose, { Schema, Document } from 'mongoose';

/**
 * 7 Supported Business Scenarios for Strategic Workforce Planning
 */
export type WorkforceScenarioType =
  | 'Business Growth'
  | 'High Attrition'
  | 'Department Expansion'
  | 'New Projects'
  | 'Hiring Freeze'
  | 'Skill Shortages'
  | 'Budget Reduction';

/**
 * Structural definition for hiring needs generated by a scenario
 */
export interface IHiringRequirement {
  role: string;
  department: string;
  headcountNeeded: number;
  estimatedCostPerHireINR: number;
  priority: 'Low' | 'Medium' | 'High' | 'Critical';
}

/**
 * Structural definition for skill gap metrics identified in a scenario
 */
export interface ISkillGapDetail {
  skillName: string;
  currentProficiencyAverage: number;
  requiredProficiencyTarget: number;
  affectedEmployeesCount: number;
}

/**
 * Recommendation for transferring internal employees across departments
 */
export interface IInternalTransferRecommendation {
  employeeId: mongoose.Types.ObjectId;
  employeeName: string;
  sourceDepartment: string;
  targetDepartment: string;
  currentRole: string;
  targetRole: string;
  skillMatchScorePercent: number;
}

/**
 * Linkage to training modules required to upskill current workforce
 */
export interface IUpskillingNeed {
  skillName: string;
  targetDepartment: string;
  recommendedTrainingId?: mongoose.Types.ObjectId;
  trainingName: string;
  employeeCount: number;
  estimatedCostINR: number;
}

/**
 * Comprehensive financial breakdown of the scenario in Indian Rupee (₹ INR)
 */
export interface IFinancialBudgetImpactINR {
  additionalRecruitmentCostINR: number;
  additionalSalaryCostINR: number;
  trainingAndUpskillingCostINR: number;
  totalBudgetImpactINR: number;
  costSavingsINR: number;
  netFinancialChangeINR: number;
}

/**
 * Mongoose Document interface for Workforce Plan / Scenario Simulation
 */
export interface IWorkforcePlan extends Document {
  scenarioName: WorkforceScenarioType;
  title: string;
  description: string;
  parameters: {
    growthRatePercent?: number;
    attritionMultiplier?: number;
    targetDepartment?: string;
    newProjectsCount?: number;
    budgetCapINR?: number;
    freezeDurationMonths?: number;
  };
  simulatedImpact: {
    currentTotalHeadcount: number;
    projectedRequiredHeadcount: number;
    netHeadcountGap: number;
    hiringRequirements: IHiringRequirement[];
    skillGaps: ISkillGapDetail[];
    internalTransfers: IInternalTransferRecommendation[];
    upskillingNeeds: IUpskillingNeed[];
    financialImpact: IFinancialBudgetImpactINR;
  };
  status: 'Draft' | 'Simulated' | 'Approved' | 'Archived';
  createdBy: mongoose.Types.ObjectId;
  createdAt: Date;
  updatedAt: Date;
}

const WorkforcePlanSchema: Schema = new Schema(
  {
    scenarioName: {
      type: String,
      required: true,
      enum: [
        'Business Growth',
        'High Attrition',
        'Department Expansion',
        'New Projects',
        'Hiring Freeze',
        'Skill Shortages',
        'Budget Reduction',
      ],
      index: true,
    },
    title: {
      type: String,
      required: true,
      trim: true,
    },
    description: {
      type: String,
      required: true,
      trim: true,
    },
    parameters: {
      growthRatePercent: { type: Number, default: 0 },
      attritionMultiplier: { type: Number, default: 1.0 },
      targetDepartment: { type: String, trim: true },
      newProjectsCount: { type: Number, default: 0 },
      budgetCapINR: { type: Number, default: 0 },
      freezeDurationMonths: { type: Number, default: 0 },
    },
    simulatedImpact: {
      currentTotalHeadcount: { type: Number, required: true, default: 0 },
      projectedRequiredHeadcount: { type: Number, required: true, default: 0 },
      netHeadcountGap: { type: Number, required: true, default: 0 },
      hiringRequirements: [
        {
          role: { type: String, required: true },
          department: { type: String, required: true },
          headcountNeeded: { type: Number, required: true, default: 1 },
          estimatedCostPerHireINR: { type: Number, required: true, default: 0 },
          priority: {
            type: String,
            enum: ['Low', 'Medium', 'High', 'Critical'],
            default: 'Medium',
          },
        },
      ],
      skillGaps: [
        {
          skillName: { type: String, required: true },
          currentProficiencyAverage: { type: Number, default: 0 },
          requiredProficiencyTarget: { type: Number, default: 0 },
          affectedEmployeesCount: { type: Number, default: 0 },
        },
      ],
      internalTransfers: [
        {
          employeeId: { type: Schema.Types.ObjectId, ref: 'Employee', required: true },
          employeeName: { type: String, required: true },
          sourceDepartment: { type: String, required: true },
          targetDepartment: { type: String, required: true },
          currentRole: { type: String, required: true },
          targetRole: { type: String, required: true },
          skillMatchScorePercent: { type: Number, required: true, default: 0 },
        },
      ],
      upskillingNeeds: [
        {
          skillName: { type: String, required: true },
          targetDepartment: { type: String, required: true },
          recommendedTrainingId: { type: Schema.Types.ObjectId, ref: 'Training' },
          trainingName: { type: String, required: true },
          employeeCount: { type: Number, default: 0 },
          estimatedCostINR: { type: Number, default: 0 },
        },
      ],
      financialImpact: {
        additionalRecruitmentCostINR: { type: Number, default: 0 },
        additionalSalaryCostINR: { type: Number, default: 0 },
        trainingAndUpskillingCostINR: { type: Number, default: 0 },
        totalBudgetImpactINR: { type: Number, default: 0 },
        costSavingsINR: { type: Number, default: 0 },
        netFinancialChangeINR: { type: Number, default: 0 },
      },
    },
    status: {
      type: String,
      enum: ['Draft', 'Simulated', 'Approved', 'Archived'],
      default: 'Simulated',
      index: true,
    },
    createdBy: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
  },
  {
    timestamps: true,
  }
);

export default mongoose.model<IWorkforcePlan>('WorkforcePlan', WorkforcePlanSchema);
